name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true
    - name: Make graddle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  test:
    name: Run Unit Tests
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Make graddle executable
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test --stacktrace
